import AuthContext from './context/AuthContext'
import './globals.css'
import { Inter } from 'next/font/google'
import ToasterAlert from './components/Toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'PiggyBanker - Gestiona tus gastos',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          <ToasterAlert />
          {children}
        </AuthContext>
      </body>
    </html>
  )
}
